name: Sync zh Tweets to JSON files
on:
  twitter:
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY_ZH }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET_ZH }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN_ZH }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_SECRET_ZH }}
    params:
      screen_name: OwenYoung_zh
    fetchAllResultsAtFirst: true
    config:
      exportOutputs: true
      outputsMode: combine
jobs:
  sync:
    name: Sync Tweets to JSON
    runs-on: ubuntu-latest
    steps:
      - name: Create Tweet JSON
        uses: actions/github-script@v2
        env:
          OUTPUTS_PATH: ${{ on.twitter.outputs.path }}
        with:
          script: |
            const path = require('path')
            const fs = require('fs').promises
            const outputs = require(`${process.env.GITHUB_WORKSPACE}/${process.env.OUTPUTS_PATH}`)
            const promises = outputs.map((item) => {
                const createdAt = new Date(Date.parse(item.created_at))
                const tweetFilePath = `./zh/tweets/${createdAt.getUTCFullYear()}/${createdAt.getUTCMonth()+1}/${item.id_str}.json`
                return fs.mkdir(path.dirname(tweetFilePath), {
                    recursive: true
                }).then(()=>{
                  return fs.writeFile(
                      tweetFilePath,
                      JSON.stringify(item, null, 2),
                      {
                        flag: "wx"
                      }
                  ).catch((e) => {
                    if (e.code === "EEXIST") {
                      return Promise.resolve();
                    } else {
                      return Promise.reject(e);
                    }
                  });
                })

            });
            await Promise.all(promises);
            return outputs.length
      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          message: "chore: add zh tweet data"
          add: "zh/tweets/*"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
