name: Sync Tweets to JSON files
on:
  twitter:
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
    params:
      screen_name: theowenyoung
    fetchAllResultsAtFirst: true
    config:
      exportOutputs: true
      outputsMode: combine
jobs:
  sync:
    name: Sync Tweets to JSON
    runs-on: ubuntu-latest
    steps:
      - name: Create Tweet JSON
        uses: actions/github-script@v2
        env:
          OUTPUTS_PATH: ${{ on.twitter.outputs.path }}
        with:
          script: |
            const syncTweets = require(`${process.env.GITHUB_WORKSPACE}/scripts/sync-tweets`)
            const result = await syncTweets({lang:'en'})
            return result
      - name: Create Pull Request
        if: true
        uses: theowenyoung/create-pull-request@master
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "chore: new item"
          branch: new-item
          delete-branch: true
          title: New item update
