name: Build Site
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "en/**"
      - "zh/**"
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Deploy site
        uses: actionsflow/axios@v1
        with:
          url: https://theowenyoung:${{secrets.PERSONAL_TOKEN}}@api.github.com/repos/theowenyoung/theowenyoung.github.io/dispatches
          method: "POST"
          data: '{ "event_type": "redeploy"}'
      - name: deploy vercel
        run: curl ${{ secrets.VERCEL_HOOK }}
